[profile.default]
solc = "0.8.20"
evm_version = "paris"
src = "src"
out = "out"
libs = ["lib"]
extra_output = ["storageLayout"]
optimizer = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[fuzz]
runs = 10000
